### ISSUE TITLE
When does Typescript compile to Javascript

### ISSUE THREAD

**Issue by JuanAntelo** [wrzlbrmft/typescript-node-express-aws-eb#1]
Hi,

I understand that Typescript compiles to Javascript and then the Javascript becomes executed.

However, I do not see this in your program. Is it that AWS supports Typescript on Node out of the box?

**Comment by wrzlbrmft** [comment]
Hi Juan, AWS Beanstalk has Node.js support built in but also runs an `npm install` using the `package.json` file you provide with your package. The `package.json` in this repo lists TypeScript as a dependency, which Beanstalk automatically installs (among other dependencies like typings, which by the way is depricated). The TypeScript compiler (`tsc`) is called here as part of the `prestart` step:
https://github.com/wrzlbrmft/typescript-node-express-aws-eb/blob/master/src/package.json#L13
Hope that answers your question!
Cheers,
Matthias
