### ISSUE TITLE
Cannot find name 'process'

### ISSUE THREAD

**Issue by gilspringer** [wrzlbrmft/typescript-node-express-aws-eb#2]
Hello,

When i make "npm start" i have this error.
config.ts(2,8): error TS2304: Cannot find name 'process'.

And wen i push zip file to aws-eb, sh: typings: command not found

Any idea ?

Best regards

**Comment by wrzlbrmft** [comment]
Confirmed.

**Comment by wrzlbrmft** [comment]
Had to switch from deprecated typings to @types. Tested it with AWS EB, works. Can you please retry?

**Comment by gilspringer** [comment]
Nice it works !
thank you very much
